# Generated by Django 2.2.7 on 2019-11-30 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import microservice.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Microservice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[(microservice.utils.Status('IDEA'), 'Прототип'), (microservice.utils.Status('INDEV'), 'В разработке'), (microservice.utils.Status('TEST'), 'Тестируется'), (microservice.utils.Status('DEPLOYED'), 'Используется'), (microservice.utils.Status('DEPRECATED'), 'Устарел'), (microservice.utils.Status('ENDLIFE'), 'Не используется')], default=microservice.utils.Status('IDEA'), max_length=20)),
                ('description', models.TextField()),
                ('business_task', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microservice.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('microservice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microservice.Microservice')),
            ],
        ),
        migrations.CreateModel(
            name='MicroserviceTechnology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('microservice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microservice.Microservice')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microservice.Technology')),
            ],
        ),
        migrations.CreateModel(
            name='MicroserviceBind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=20)),
                ('dependant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depends_on_binds', to='microservice.Microservice')),
                ('depends_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependants_binds', to='microservice.Microservice')),
            ],
        ),
        migrations.AddField(
            model_name='microservice',
            name='depends_on',
            field=models.ManyToManyField(related_name='dependants', related_query_name='dependants', through='microservice.MicroserviceBind', to='microservice.Microservice'),
        ),
        migrations.AddField(
            model_name='microservice',
            name='tech_stack',
            field=models.ManyToManyField(related_name='microservices', related_query_name='microservices', through='microservice.MicroserviceTechnology', to='microservice.Technology'),
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('microservice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microservice.Microservice')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microservice.Department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
